# -*- coding: utf-8 -*-
"""minor2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6nmcWZiCCSpKC3UEIflaCRKWzeZMFlg
"""

F="converted_image.bmp"; W=80; A="%@#*+=-:."

def p(v): return A[v*(len(A)-1)//255]

with open(F,"rb") as f:
    f.seek(18); w=int.from_bytes(f.read(4),"little"); h=int.from_bytes(f.read(4),"little")
    f.seek(10); f.seek(int.from_bytes(f.read(4),"little"))
    pad=(4-(w*3)%4)%4; img=[]
    for _ in range(h):
        r=[]
        for _ in range(w):
            b=f.read(1)[0]; g=f.read(1)[0]; rch=f.read(1)[0]
            r.append((rch+g+b)//3)
        f.read(pad); img.append(r)

img=img[::-1]; H=int((h/w)*W*0.5)

for y in range(H):
    print("".join(
        " " if img[int(y*h/H)][int(x*w/W)]>200
        else p(img[int(y*h/H)][int(x*w/W)])
        for x in range(W)
    ))

"""#####ASCII ART #####"""





